server:
  port: 9006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

zuul:
  ignored-services: '*'
  routes:
    users:
      path: /users/**
      service-id: USER-SERVICE
