server:
  port: 9004
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  cloud:
    config:
      discovery:
        service-id: config-service
      fail-fast: true
      retry:
        max-attempts: 2